import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import ProviderInitialize from '@web/ui/provider/initialize';
import ProviderSync from '@web/ui/provider/sync';
import { APP_NAME, DEFAULT_COLOR_SCHEME } from '@repo/constants';
import { createClientcloudbaseServer } from '@repo/cloudbase';
import { getCookieServer } from '@repo/utils';
import { COOKIE_NAME } from '@repo/constants';
import ProviderMantine from '@web/ui/provider/mantine';
import { MantineColorScheme, mantineHtmlProps } from '@mantine/core';
import { getAppTheme } from '@web/theme';
import { getAppResolver } from '@web/resolver';

import './globals.css';

// Import styles of packages that you've installed.
// All packages except `@mantine/hooks` require styles imports
import '@mantine/core/styles.css';
import '@mantine/dates/styles.css';
// ‼️ import schedule styles after core and dates package styles
import '@mantine/schedule/styles.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const supabase = await createClientcloudbaseServer();
  const { data: session } = await supabase.auth.getUser();

  // 1. Get the CALCULATED theme from middleware (not the 'auto' state)
  const theme = (await getCookieServer(COOKIE_NAME.COLOR_SCHEME)) || DEFAULT_COLOR_SCHEME;
  const resolvedTheme = (theme || DEFAULT_COLOR_SCHEME) as MantineColorScheme;

  return (
    <html
      lang="en"
      {...mantineHtmlProps}
      data-mantine-color-scheme={resolvedTheme}
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <meta charSet="UTF-8" />

        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
          viewport-fit="cover"
        />

        {/* <ColorSchemeScript defaultColorScheme={resolvedTheme} /> */}
      </head>

      <body className="min-h-full flex flex-col">
        <ProviderMantine
          options={{ withNotifications: true }}
          colorScheme={resolvedTheme}
          theme={getAppTheme}
          cssVariablesResolver={getAppResolver}
        >
          <ProviderInitialize props={{ sessionUser: session.user }}>
            <ProviderSync>{children}</ProviderSync>
          </ProviderInitialize>
        </ProviderMantine>
      </body>
    </html>
  );
}
